import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../public/vendor/pokevault/css/7fb674adbec2a7c3.css";
import "../public/vendor/pokevault/css/21f418c2620c223b.css";
import Footer from "./components/footer";
import Navbar from "./components/nav";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {" "}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
